
FROM nvidia/cuda:10.2-devel-ubuntu18.04

# install curl
RUN apt update -y && \\ 
    apt update && \\ 
    apt upgrade && \\ 
    apt install curl -y && \\ 
    apt-get install git && \\
    apt-get install git-all